spring:
  application:
    name: analytics-service

  # Disable Config Server for Docker
  cloud:
    config:
      enabled: false
      fail-fast: false

  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:yushan_analytics}
    username: ${DB_USERNAME:yushan_analytics}
    password: ${DB_PASSWORD:ahanj123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate  # Use validate in Docker, Flyway manages schema
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

  # MyBatis Configuration
  mybatis:
    mapper-locations: classpath:/mapper/**Mapper.xml
    type-aliases-package: com.yushan.analytics_service.entity
    config-location: classpath:config/mybatis-config.xml

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  cache:
    type: redis

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    enabled: ${SPRING_KAFKA_ENABLED:false}

# Server Configuration
server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: /
  compression:
    enabled: true

# Eureka Client Configuration
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://yushan-eureka-registry:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      version: 1.0.0
      description: Analytics and ranking service

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:docker-secret-key-for-jwt-token-generation-and-validation-minimum-256-bits}
  issuer: ${JWT_ISSUER:yushan-docker-service}
  algorithm: ${JWT_ALGORITHM:HS256}
  expiration: ${JWT_EXPIRATION:86400000}

# Service URLs for Feign Clients - Use container names
services:
  user:
    name: ${USER_SERVICE_NAME:user-service}
    url: ${USER_SERVICE_URL:http://yushan-user-service:8080}
  content:
    name: ${CONTENT_SERVICE_NAME:content-service}
    url: ${CONTENT_SERVICE_URL:http://yushan-content-service:8080}

# Analytics Configuration
analytics:
  aggregation:
    batch-size: ${ANALYTICS_BATCH_SIZE:1000}
    interval: ${ANALYTICS_AGGREGATION_INTERVAL:300}
  retention:
    raw-data-days: ${ANALYTICS_RETENTION_DAYS:90}
    aggregated-data-days: ${ANALYTICS_AGGREGATED_DATA_DAYS:365}
  cache:
    ttl: ${ANALYTICS_CACHE_TTL:600}
  reports:
    max-page-size: ${ANALYTICS_MAX_PAGE_SIZE:1000}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# Logging Configuration
logging:
  level:
    com.yushan.analytics: INFO  # Changed to INFO for Docker to reduce noise
    org.springframework.cloud: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"