# Docker-specific configuration
spring:
  # PostgreSQL Configuration for Docker
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:yushan_analytics}
    username: ${DB_USERNAME:yushan_analytics}
    password: ${DB_PASSWORD:change_me_in_production}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 60000

  # Redis Configuration for Docker
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
        shutdown-timeout: 100ms

  # Kafka Configuration (disabled for now)
  kafka:
    enabled: ${SPRING_KAFKA_ENABLED:false}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Eureka Client Configuration for Docker
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://yushan-eureka-registry:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      version: 1.0.0
      description: Analytics and ranking service

# Logging for Docker (less verbose)
logging:
  level:
    com.yushan.analytics: INFO
    org.springframework.cloud: INFO
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: INFO